name: oil_erp
description: "OIL ERP App"
publish_to: "none"
version: 1.0.2+1001

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.8.0+1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.0
  flutter_map: ^8.2.1
  flutter_platform_widgets: ^9.0.0
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.2
  go_router: ^16.0.0
  hive: ^2.2.3
  latlong2: ^0.9.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^6.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/html/